// web/src/svelte/Person.svelte
<script>
import { initials, personFrom } from "../person.js";

let {
  account,
  avatarUrl = null,
  size = 44,
  onSignOut = null,
  signOutLabel = "Sign out",
  class: className = "",
} = $props();

const info = $derived(personFrom(account));

let broken = $state(null);
const showsAvatar = $derived(avatarUrl && broken !== avatarUrl);
</script>

<div class={["masks-person", className].filter(Boolean).join(" ")}>
  {#if showsAvatar}
    <img
      class="masks-person-avatar"
      src={avatarUrl}
      alt=""
      width={size}
      height={size}
      onerror={() => (broken = avatarUrl)}
    />
  {:else}
    <span
      class="masks-person-avatar masks-person-avatar-letters"
      style="width:{size}px;height:{size}px;font-size:{Math.round(size * 0.38)}px"
    >
      {initials(info.name)}
    </span>
  {/if}

  <div class="masks-person-who">
    <span class="masks-person-name">{info.name}</span>

    {#if info.details.length || info.unconfirmed}
      <span class="masks-person-sub">
        {info.details.join(" · ")}
        {#if info.unconfirmed}
          <span class="masks-person-note">unconfirmed</span>
        {/if}
      </span>
    {/if}

    {#if info.organization}
      <span class="masks-person-org">
        {info.organization.name}
        <span class="masks-person-org-role">{info.role}</span>
      </span>
    {/if}

    {#if info.manager}
      <span class="masks-person-role">Manager</span>
    {/if}
  </div>

  {#if onSignOut}
    <button type="button" class="masks-person-signout" onclick={onSignOut}>
      {signOutLabel}
    </button>
  {/if}
</div>

// web/src/react/Person.tsx
import { useState } from "react";
import { initials, personFrom } from "../person.js";
import type { Account } from "../types.js";

export interface PersonProps {
  account: Account;
  avatarUrl?: string | null;
  size?: number;
  onSignOut?: () => void;
  signOutLabel?: string;
  className?: string;
}

export function Person({
  account,
  avatarUrl = null,
  size = 44,
  onSignOut,
  signOutLabel = "Sign out",
  className,
}: PersonProps) {
  const info = personFrom(account);
  const [broken, setBroken] = useState<string | null>(null);
  const showsAvatar = avatarUrl && broken !== avatarUrl;

  return (
    <div className={["masks-person", className].filter(Boolean).join(" ")}>
      {showsAvatar ? (
        <img
          className="masks-person-avatar"
          src={avatarUrl}
          alt=""
          width={size}
          height={size}
          onError={() => setBroken(avatarUrl)}
        />
      ) : (
        <span
          className="masks-person-avatar masks-person-avatar-letters"
          style={{
            width: size,
            height: size,
            fontSize: Math.round(size * 0.38),
          }}
        >
          {initials(info.name)}
        </span>
      )}

      <div className="masks-person-who">
        <span className="masks-person-name">{info.name}</span>

        {(info.details.length > 0 || info.unconfirmed) && (
          <span className="masks-person-sub">
            {info.details.join(" · ")}
            {info.unconfirmed && (
              <span className="masks-person-note">unconfirmed</span>
            )}
          </span>
        )}

        {info.organization && (
          <span className="masks-person-org">
            {info.organization.name}
            <span className="masks-person-org-role">{info.role}</span>
          </span>
        )}

        {info.manager && <span className="masks-person-role">Manager</span>}
      </div>

      {onSignOut && (
        <button
          type="button"
          className="masks-person-signout"
          onClick={onSignOut}
        >
          {signOutLabel}
        </button>
      )}
    </div>
  );
}
